---
name: libs/infinity_emb - Release docker

on:
  release:
    types: [published]

env:
  POETRY_VERSION: "1.7.1"
  WORKDIR: "libs/infinity_emb"

jobs:
  docker-container-push:
    uses:
      ./.github/workflows/release_docker_container.yaml
    with:
      # working-directory: libs/infinity_emb
      dockerfile: libs/infinity_emb/Dockerfile
      image: michaelf34/infinity
    secrets: inherit

  modal-deploy:
    needs: docker-container-push
    uses:
      ./.github/workflows/release_modal_com.yaml
    secrets: inherit